Description: Simple template to store WarpStream API key in AWS Secrets Manager
Parameters:
  ClusterName:
    Type: String
    Description: User friendly name of the cluster
  ClusterId:
    Type: String
    Description: The Cluster ID
  WarpStreamApiKey:
    Type: String
    Description: The WarpStream API Key
    NoEcho: true
  AgentPoolName:
    Type: String
    Description: WarpStream agent pool name
Resources:
  WarpStreamSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: /kafka/warpstream/${ClusterName}
        - Key: ClusterName
          Value:
            Ref: ClusterName
        - Key: ClusterId
          Value:
            Ref: ClusterId
      Name:
        Fn::Sub: /kafka/warpstream/${ClusterName}
      SecretString:
        Fn::Sub: |
          {
            "api_key": "${WarpStreamApiKey}",
            "cluster_id": "${ClusterId}",
            "agent_pool_name": "${AgentPoolName}"
          }
Outputs:
  SecretArn:
    Value:
      Ref: WarpStreamSecret
